name: eda
channels:
  - defaults
dependencies:
  - pip=20.3.3
  - python=3.8
  - pip:
      - wandb==0.10.31
      - jupyterlab==3.0.12
      - seaborn==0.11.1
      - pandas==1.2.3
      - pandas-profiling==2.11.0
      - pyarrow==2.0
      - protobuf==3.20
      - numpy==1.20