name: components
channels:
  - defaults
dependencies:
  - pip=20.3.3
  - python=3.8
  - pip:
      - wandb==0.10.31
      - mlflow==1.14.1
      - pyyaml==5.3.1
      - hydra-core==1.0.6
      - protobuf==3.20
      - numpy==1.20