name: basic_cleaning
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
      - pandas==1.1.4
      - mlflow==1.14.1
      - scikit-learn==0.24.1
      - matplotlib==3.2.2
      - pillow==8.1.2
      - protobuf==3.20
      - numpy==1.20
